const users = [
  {
    id: '1',
    name: 'Dr. Sarah Johnson',
    email: 'sarah.johnson@edu.com',
    role: 'Teacher',
    status: 'Active',
    contactInfo: '+1 (555) 001-0001',
  },
  {
    id: '2',
    name: 'Prof. Michael Chen',
    email: 'michael.chen@edu.com',
    role: 'Teacher',
    status: 'Inactive',
    contactInfo: '+1 (555) 001-0002',
  },
  {
    id: '3',
    name: 'Ms. Emily Davis',
    email: 'emily.davis@edu.com',
    role: 'Teacher',
    status: 'Active',
    contactInfo: '+1 (555) 001-0003',
  },
  {
    id: '4',
    name: 'John Smith',
    email: 'john.smith@student.edu',
    role: 'Student',
    status: 'Inactive',
    enrolledCourses: 5,
    contactInfo: '+1 (555) 100-0001',
    dateOfBirth: '2005-03-15',
  },
  {
    id: '5',
    name: 'Emma Wilson',
    email: 'emma.wilson@student.edu',
    role: 'Student',
    status: 'Active',
    enrolledCourses: 4,
    contactInfo: '+1 (555) 100-0002',
    dateOfBirth: '2006-07-22',
  },
  {
    id: '6',
    name: 'Oliver Brown',
    email: 'oliver.brown@student.edu',
    role: 'Student',
    status: 'Inactive',
    enrolledCourses: 3,
    contactInfo: '+1 (555) 100-0003',
    dateOfBirth: '2005-11-08',
  },
  {
    id: '7',
    name: 'Sophia Martinez',
    email: 'sophia.martinez@student.edu',
    role: 'Student',
    status: 'Active',
    enrolledCourses: 6,
    contactInfo: '+1 (555) 100-0004',
    dateOfBirth: '2006-01-30',
  },
  {
    id: '8',
    name: 'Liam Anderson',
    email: 'liam.anderson@student.edu',
    role: 'Student',
    status: 'Active',
    enrolledCourses: 5,
    contactInfo: '+1 (555) 100-0005',
    dateOfBirth: '2005-09-14',
  },
];

export default users;
